version: '2'

services:

  mysql:
    image: mariadb
    container_name: mysql-casadocodigo
    ports:
      - 3306:3306
    volumes:
      - ./src/test/resources/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: casadocodigo
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-casadocodigo
    links:
      - mysql:db
    ports:
      - 8181:80
    environment:
      MYSQL_USER: root
    depends_on:
      - mysql