version: '2'

services:

  mysql:
    image: mariadb
    container_name: mysql-listavip
    ports:
      - 3306:3306
    volumes:
      - /home/paulo/workspace/listavip/src/main/resources/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: listavip
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-listavip
    links:
      - mysql:db
    ports:
      - 8181:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql